version: "3"
services:
  todoback:
    build: todo-app/back-end/
    restart: always
    ports:
      - 3001:3001
    networks:
      - todo-network
  
  todofront:
    build: todo-app/front-end
    restart: always
    ports:
      - 3000:3000
    networks:
      - todo-network
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todotests:
    build: todo-app/tests
    restart: always
    networks:
      - todo-network
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
    
networks:
  todo-network:
